In [1]:
import numpy as np

In [2]:
# Single Diamensional Array
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [3]:
a+4

array([14, 24, 34, 44, 54])

In [5]:
a*3

array([ 30,  60,  90, 120, 150])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(5,)

In [9]:
a.ndim

1

In [11]:
a.dtype

dtype('int64')

In [12]:
a.size

5

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a =np.arange(2,19)

In [23]:
np.linspace(3,30,10)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [24]:
a+3

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [25]:
np.where(a%2==0,"Even","Odd")

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even'],
      dtype='<U4')

In [28]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
a=np.array(np.random.randint(1,100,(4,2)))

In [32]:
a

array([[79, 93],
       [55, 74],
       [28, 25],
       [28, 80]], dtype=int32)

In [35]:
a[0,1]

np.int32(93)

In [37]:
a[1:,:]

array([[55, 74],
       [28, 25],
       [28, 80]], dtype=int32)

In [38]:
a.sum()

np.int64(462)

In [39]:
a.mean()

np.float64(57.75)

In [42]:
a.ravel()

array([79, 93, 55, 74, 28, 25, 28, 80], dtype=int32)

In [44]:
a.flatten()

array([79, 93, 55, 74, 28, 25, 28, 80], dtype=int32)

In [47]:
a

array([[79, 93],
       [55, 74],
       [28, 25],
       [28, 80]], dtype=int32)

In [53]:
(a<40) &(a>10)

array([[False, False],
       [False, False],
       [ True,  True],
       [ True, False]])

In [54]:
a[(a<40) &(a>10)]

array([28, 25, 28], dtype=int32)